// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"W-chat/config"
	"W-chat/src/httpserver"
	"W-chat/src/httpserver/api/handler"
	"W-chat/src/httpserver/api/handler/web"
	"W-chat/src/httpserver/api/handler/web/v1"
	"W-chat/src/httpserver/api/router"
)

// Injectors from wire.go:

func HttpServerInjector(conf *config.Config) *httpserver.Basic {
	auth := &v1.Auth{
		Config: conf,
	}
	webV1 := &web.V1{
		Auth: auth,
	}
	webHandler := &web.Handler{
		V1: webV1,
	}
	handlerHandler := &handler.Handler{
		WebApi: webHandler,
	}
	engine := router.NewRouter(conf, handlerHandler)
	basic := &httpserver.Basic{
		Config: conf,
		Gin:    engine,
	}
	return basic
}
