// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"W-chat/config"
	"W-chat/src/httpserver"
	"W-chat/src/httpserver/api/handler"
	"W-chat/src/httpserver/api/handler/web"
	"W-chat/src/httpserver/api/handler/web/v1"
	"W-chat/src/httpserver/api/router"
	"W-chat/src/methods"
	"W-chat/src/repository"
	"W-chat/src/repository/database"
	"github.com/google/wire"
)

// Injectors from wire.go:

func HttpServerInjector(conf *config.Config) *httpserver.Basic {
	db := repository.NewMySQLClient(conf)
	users := database.NewUsers(db)
	authMethods := methods.NewAuthMethodsObj(users)
	methodsMethods := &methods.Methods{
		Auth: authMethods,
	}
	auth := &v1.Auth{
		Config:  conf,
		Methods: methodsMethods,
	}
	webV1 := &web.V1{
		Auth: auth,
	}
	webHandler := &web.Handler{
		V1: webV1,
	}
	handlerHandler := &handler.Handler{
		WebApi: webHandler,
	}
	engine := router.NewRouter(conf, handlerHandler)
	basic := &httpserver.Basic{
		Config: conf,
		Gin:    engine,
	}
	return basic
}

// wire.go:

var providerSet = wire.NewSet(repository.NewMySQLClient, methods.ProviderSet)
